export const Skill = Object.freeze({
  REACT: "React",
  JAVASCRIPT: "JavaScript",
  CSS: "CSS",
  SASS: "SASS",
  HTML: "HTML",
  JAVA: "Java",
  PYTHON: "Python",
  C: "C",
  SQL: "SQL",
  GIT: "Git",
  SELENIUM: "Selenium",
  AI: "AI",
  API_DEVELOPMENT: "API Development",
  POSTGRESQL: "PostgreSQL",
  POSTMAN: "Postman",
  SPRINGBOOT: "Springboot",
  GOOGLE_CLOUD_PLATFORM: "Google Cloud Platform",
  OPENCV: "OpenCV",
  TENSORFLOW: "Tensorflow",
  ANDROID_STUDIO: "Android Studio",
  IBM_DB2: "IBM Db2",
  FLUTTER: "Flutter",
  FIREBASE: "Firebase",
  DIALOGFLOW: "DialogFlow",
  LANGCHAIN: "LangChain",
  AWS: "AWS",
  UNITY: "Unity",
  CSHARP: "C#",
  MAPBOXSDK: "MapboxSDK",
  AUGMENTED_REALITY: "Augmented Reality",
  IMAGE_CLASSIFICATION: "Image Classification",
  IBM_DB2: "IBM Db2",
  FLUTTER: "Flutter",
  TYPESCRIPT: "TypeScript",
});

export const RESUME_LINK =
  "https://drive.google.com/file/d/1MBhwr2U7-Yt23jNwkxpvLhPw35goi6Kk/view?usp=sharing";
